ListenAndServe: :3031
ScannerCMD: sudo scanimage -d 'hpaio:/usb/HP_LaserJet_M1005?serial=KJ6NYS4' --format jpeg --mode color --resolution 200 > %s
BaseAuth: true
BaseAuthUser: z
BaseAuthPasswd: zzz
BaseAuthSuper: true
BaseAuthSuperUser: zz
BaseAuthSuperPasswd: zzz
